### ISSUE TITLE
アプリ接続の削除ができない

### ISSUE THREAD

**Issue by konosuke115** [MicrosoftDocs/CloudAppSecurityDocs.ja-jp#5]
AWSとのアプリ接続をテストしたのですが、セキュリティの構成では接続エラーとなってしまいます。

また、一度追加した接続アプリの削除方法が分からないので、方法を教えていただきたいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3bf4839c-f4e3-5808-c608-f2795f7b640d
* Version Independent ID: 3ccbc129-d930-eb79-a034-365b89f88a13
* Content: [Cloud App Security を使用したアマゾンウェブサービスの接続](https://docs.microsoft.com/ja-jp/cloud-app-security/connect-aws-to-microsoft-cloud-app-security)
* Content Source: [CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md](https://github.com/MicrosoftDocs/CloudAppSecurityDocs.ja-jp/blob/live/CloudAppSecurityDocs/connect-aws-to-microsoft-cloud-app-security.md)
* Service: **cloud-app-security**
* Product: ****
* Technology: ****
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by srvbpigh** [comment]
Hello, @konosuke115
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@konosuke115
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
